### ISSUE TITLE
[meta] Release grid_map_geo binaries with bloom

### ISSUE THREAD

**Issue by Ryanf55** [ethz-asl/grid_map_geo#50]
# Purpose

This issue is to keep track of the tasks needed to release this repository through bloom. Once the library has a stable-ish API, it makes sense to release as binaries instead of requiring consumers, like terrain-navigation, to compile this from source. 

# Pre-requisites

* [ ] #35 including both ArduPilot VRT support and dynamic load/unload
* [ ] Separate out the ROS layer from the core grid_map_geo library, perhaps by dividing it into two packages
* [ ] Add an example of a plane flying in SITL and demonstrate query of map data along the flight and visualize in rviz
* [ ] Finalize how users should specify map size limits
* [ ] Verify that poor configuration will not cause a runtime crash of the library (add some test cases that can be run in CI)

# Final checks

* [ ] Verify the package.xml has a version starting with 0, which lets consumers know this is experimental and not necessarily ABI stable yet (We can release version 1.0 once terrain navigation has been used by enough users)
* [ ] Generate a changelog
* [ ] Follow this [tutorial](https://docs.ros.org/en/humble/index.html) to release the package
